//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmiralBattiV2.ModelV3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayerInfoV3Entities1 : DbContext
    {
        public PlayerInfoV3Entities1()
            : base("name=PlayerInfoV3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirstPlayer> FirstPlayers { get; set; }
        public virtual DbSet<RivalPlayer> RivalPlayers { get; set; }
    }
}
